xbapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include

urlpatterns = patterns('xbapp.views',
    url(r'^$', 'inicio'),
    url(r'^login$', 'login'),
    url(r'^logout$', 'logout'),
    url(r'^perfil$', 'perfil'),
    url(r'^captura$', 'captura'),
    url(r'^proyecto$', 'proyecto'),
    url(r'^estadisticas$', 'estadisticas'),
    url(r'^contacto$', 'contacto'),
)

urlpatterns += patterns('xbapp.api',
    url(r'^api$', 'inicio'),
    url(r'^api/registro$', 'registro'),
    url(r'^api/login$', 'login'),
    url(r'^api/token$', 'obtener_token'),
    url(r'^api/w/ruta$', 'registra_ruta'),
    url(r'^api/w/lugar$', 'registra_lugar'),
    url(r'^api/r/rutas$', 'rutas'),
)

xbapp/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid1
import datetime

MODELO_USUARIO = get_user_model()

def crea_uid():
    return str(uuid1())

def existe_usuario(**kwargs):
    try:
        MODELO_USUARIO.objects.get(**kwargs)
        return True
    except MODELO_USUARIO.DoesNotExist:
        return False

class Ciclista(models.Model):
    """Define a un usuario del sistema"""
    nombre              = models.CharField(max_length=70, blank=True)
    facebook            = models.CharField(max_length=70, blank=True)
    twitter             = models.CharField(max_length=70, blank=True)
    score               = models.IntegerField(default=0)
    sexo                = models.CharField(max_length=1, choices=(
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ), default='M')
    fecha_nacimiento    = models.DateField(blank=True, null=True)
    fecha_registro      = models.DateField(auto_now_add=True)
    usuario             = models.OneToOneField(get_user_model())
    token               = models.CharField(max_length=36, default=crea_uid, unique=True)

    def __unicode__(self):
        return self.nombre

    def edad(self):
        return (datetime.date.today()-self.fecha_nacimiento).days/365 if self.fecha_nacimiento else 0

class Ruta(models.Model):
    """Una ruta recorrida y marcada por un usuario"""
    hora_inicio         = models.DateTimeField()
    hora_fin            = models.DateTimeField()
    ciclista            = models.ForeignKey(Ciclista)
    longitud            = models.FloatField()
    desplazamiento      = models.FloatField()

class Punto(models.Model):
    """Define un punto de una ruta marcado por el GPS"""
    latitud             = models.FloatField()
    longitud            = models.FloatField()
    altitud             = models.IntegerField()
    ruta                = models.ForeignKey(Ruta, related_name='puntos')

    def __unicode__(self):
        return u"(%fº, %fº) a %d msnm"%(self.latitud, self.longitud, self.altitud)

class TipoLugar(models.Model):
    """Sirve para clasificar los lugares que encuentra el ciclista, como
    talleres o biciestacionamientos"""
    nombre              = models.CharField(max_length=50, blank=True)
    codigo              = models.CharField(max_length=50, default='', unique=True, blank=True)

    def save(self):
        self.nombre = self.nombre.lower()
        self.codigo = self.codigo.lower()
        if self.nombre and not self.codigo:
            self.codigo = self.nombre.replace(' ', '_')
        if self.codigo and not self.nombre:
            self.nombre = self.codigo.replace('_', ' ')
        self.nombre = self.nombre.capitalize()
        super(TipoLugar, self).save()

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'tipos de lugar'

class Lugar(models.Model):
    """Un punto importante para un ciclista, como un taller"""
    nombre              = models.CharField(max_length=70, blank=True)
    direccion           = models.CharField(max_length=140, blank=True)
    latitud             = models.FloatField()
    longitud            = models.FloatField()
    altitud             = models.IntegerField()
    tipo                = models.ForeignKey(TipoLugar)
    registrante         = models.ForeignKey(Ciclista)

    def __unicode__(self):
        return u"%s (%s)"%(self.nombre, self.tipo)

    class Meta:
        verbose_name_plural = 'lugares'

class TipoSuceso(models.Model):
    """ayuda a clasificar sucesos en la actividad vial del ciclista"""
    nombre              = models.CharField(max_length=50)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'tipos de suceso'

class Suceso(models.Model):
    """Un suceso vial reportado por un ciclista o peatón con la aplicación"""
    ciclista            = models.ForeignKey(Ciclista)
    descripcion         = models.CharField(max_length=140)
    latitud             = models.FloatField()
    longitud            = models.FloatField()
    altitud             = models.IntegerField()
    tipo                = models.ForeignKey(TipoSuceso)
    hora                = models.DateTimeField()

    def __unicode__(self):
        return self.descripcion

xbapp/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from xbapp.models import Lugar, Ciclista
import re

MODELO_USUARIO = get_user_model()

def likethis(diccionario, referencia):
    """Compara 'diccionario' con 'referencia' (otro diccionario) en términos de llaves
    y tipos de datos de valores, recursivamente"""
    for llave, valor in referencia.iteritems():
        if not diccionario.has_key(llave):
            raise ValidationError('falta_llave')
        if type(diccionario[llave]) != type(valor) and not (type(diccionario[llave])==unicode and type(valor)==str):
            raise ValidationError('tipo_valor')

def valida_ruta(ruta_dict):
    if  'hora_inicio' in ruta_dict and \
        'hora_fin' in ruta_dict and \
        'puntos' in ruta_dict and \
        'longitud' in ruta_dict and \
        'desplazamiento' in ruta_dict and \
        re.match('\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', ruta_dict['hora_inicio']) and \
        re.match('\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', ruta_dict['hora_fin']):
        if type(ruta_dict['puntos'])==list and type(ruta_dict['longitud'])==float and type(ruta_dict['desplazamiento'])==float:
            for punto in ruta_dict['puntos']:
                if 'latitud' in punto and 'longitud' in punto and 'altitud' in punto:
                    if type(punto['latitud']) != float or type(punto['longitud']) != float or type(punto['altitud']) != int:
                        raise ValidationError('formato de ruta invalido (tipo de dato)')
                    else:
                        return
                else:
                    raise ValidationError('formato de ruta invalido (valor faltante)')
            return
    else:
        raise ValidationError('formato de ruta invalido (cabecera faltante)')

def valida_lugar(lugar_dict):
    return likethis(lugar_dict, {
        "nombre"    : "Rojas bikes",
        "direccion" : "2º priv. bis de josé mancisidor #157-b",
        "latitud"   : 93.2323,
        "longitud"  : 23.4343,
        "altitud"   : 1420,
        "tipo"      : "biciestacionamiento",  #puede ser también "taller" o "gasolinera"
    })

def valida_correo(correo):
    try:
        MODELO_USUARIO.objects.get(username=correo)
        raise ValidationError('ya existe este campo')
    except MODELO_USUARIO.DoesNotExist:
        pass

class APIRegistroForm(forms.Form):
    nombre              = forms.CharField(min_length=3, max_length=70)
    sexo                = forms.ChoiceField(choices=(
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ))
    fecha_nacimiento    = forms.DateField()
    correo              = forms.EmailField(validators=[valida_correo])
    password            = forms.CharField(min_length=6)

class APILoginForm(forms.Form):
    correo              = forms.EmailField()
    password            = forms.CharField(min_length=6)

class LugarForm(forms.ModelForm):
    class Meta:
        model = Lugar
        exclude = ('registrante',)

class CiclistaForm(forms.ModelForm):
    nombre              = forms.CharField(required=True)
    fecha_nacimiento    = forms.DateField(widget=forms.DateInput(attrs={'placeholder': 'dd/mm/AAAA'}))
    class Meta:
        model = Ciclista
        exclude = ('token', 'usuario', 'score')

xbapp/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.http import require_GET, require_POST
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from xbapp.forms import LugarForm, APILoginForm, CiclistaForm
from xbapp.models import existe_usuario, Ruta, Ciclista
from xbapp.queries import cuenta_ciclistas
from django.contrib.auth import get_user_model
from django.conf import settings
import datetime

if settings.DEBUG:
    from pprint import pprint

MODELO_USUARIO = get_user_model()

def inicio(request):
    data = {}
    return render_to_response('xbapp/inicio.html', data, context_instance=RequestContext(request))

@require_POST
def login(request):
    """Procesa el login"""
    if not request.user.is_authenticated():
        username = request.POST.get('correo')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                messages.success(request, '¡Bienvenido!')
            else:
                messages.error(request, 'Lo sentimos, esta cuenta está desactivada')
        else:
            # buscamos el correo, si no existe, lo mandamos a registro
            if existe_usuario(email=request.POST.get('correo', '')):
                messages.error(request, 'contraseña incorrecta')
            else:
                # lo procedemos a inscribir
                formulario = APILoginForm(request.POST)
                if formulario.is_valid():
                    nuevo_usuario = MODELO_USUARIO(username=username, email=username)
                    nuevo_usuario.set_password(password)
                    nuevo_usuario.save()
                    user = auth.authenticate(username=username, password=password)
                    auth.login(request, user)
                    messages.success(request, 'Te has registrado!!')
                    messages.info(request, 'Termina de llenar tu perfil')
                    return HttpResponseRedirect('/perfil')
                else:
                    messages.warning(request, 'datos de registro inválidos')
                    return HttpResponseRedirect('/')
            messages.error(request, 'Nadie registrado con ese correo, verifique por favor')
    else:
        messages.warning(request, 'Ya tienes una sesión')
    return HttpResponseRedirect('/')

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, 'Nos vemos pronto')
    return HttpResponseRedirect('/')

@login_required
def captura(request):
    data = {
        'formulario': LugarForm()
    }
    if request.method == 'POST':
        formulario = LugarForm(request.POST)
        if formulario.is_valid():
            lugar = formulario.save(commit=False)
            lugar.registrante = request.user.ciclista
            lugar.save()
            messages.success(request, 'Gracias!! dato guardado')
        else:
            messages.error(request, 'Hay errores con los campos del formulario')
            data['formulario'] = formulario
    return render_to_response('xbapp/captura.html', data, RequestContext(request))

@login_required
def perfil(request):
    data = {
        'formulario': CiclistaForm(instance=request.user.ciclista)
    }
    if request.method == 'POST':
        formulario = CiclistaForm(request.POST, instance=request.user.ciclista)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Datos actualizados!')
        else:
            messages.error(request, 'Alguno de los datos no es válido')
        data['formulario'] = formulario
    return render_to_response('xbapp/perfil.html', data, RequestContext(request))

def proyecto(request):
    data = {

    }
    return render_to_response('xbapp/proyecto.html', data, RequestContext(request))

def estadisticas(request):
    num_ciclistas = Ciclista.objects.all()
    total = num_ciclistas.count()

    num_hombres = num_ciclistas.filter(sexo='M').count()
    num_mujeres = total-num_hombres

    hombres = float(num_hombres)/total*100
    mujeres = 100-hombres

    hoy = datetime.date.today()

    edad_media = sum([c.edad() for c in num_ciclistas if c.fecha_nacimiento])/(num_ciclistas.filter(fecha_nacimiento__isnull=False).count())

    edades = [{
        'rango': '%d-%d'%(i, i+10),
        'cantidad': cuenta_ciclistas(i, i+10),
        'porcentaje': float(cuenta_ciclistas(i, i+10))/total*100,
    } for i in [j*10 for j in xrange(10)]]

    if settings.DEBUG:
        pprint(edades)

    data = {
        'nrutas': Ruta.objects.count(),
        'nciclistas': total,
        'hombres': '%.2f'%hombres,
        'mujeres': '%.2f'%mujeres,
        'num_hombres': num_hombres,
        'num_mujeres': num_mujeres,
        'edad_media': edad_media,
        'edades': edades
    }
    return render_to_response('xbapp/estadisticas.html', data, RequestContext(request))

def contacto(request):
    data = {

    }
    return render_to_response('xbapp/contacto.html', data, RequestContext(request))

xbapp/templates/xbapp/captura.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles bootstrap_tags %}

{% block contenido %}
	{% addtoblock 'css' %}
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/mapa.css' %}">
	{% endaddtoblock %}
	{% addtoblock 'js' %}
		<script type="text/javascript" language="javascript">
			$(document).ready(function(){
				$("#add-lugar-form input, #add-lugar-form select").addClass('form-control');
			});
		</script>
		<script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=geometry"></script>
		<script src="{% static 'xbapp/js/mapa.js' %}"></script>
		<script src="{% static 'xbapp/js/lugares.js' %}"></script>
	{% endaddtoblock %}
	<div class="row">
		<div class="col-md-12">
			<p class="lead">
				Selecciona en el mapa la ubicación del lugar que quieres registrar
			</p>
			<p>Puede ser un taller, un estaionamiento que admite bicicletas, una gasolinera u otro punto importante para tu labor como ciclista</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<form id="add-lugar-form" class="form-horizontal" method="post">
				{% csrf_token %}
				{% form_horizontal formulario %}
				<div class="form-group">
					<div class="col-md-10 col-md-offset-2">
						<input type="submit" value="Guardar" class="btn btn-success">
					</div>
				</div>
			</form>
		</div>
		<div class="col-md-6">
			<div id="map_canvas"></div>
		</div>
	</div>
{% endblock %}

xbapp/templates/xbapp/capturas.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles %}

{% block contenido %}
	<div class="row">
		<div class="col-md-6">
			<a href="" class="btn btn-lg btn-success btn-block">de</a>
		</div>
		<div class="col-md-6">
			<a href="" class="btn btn-lg btn-success btn-block">de</a>
		</div>
	</div>
{% endblock %}

xbapp/templates/xbapp/contacto.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles %}

{% block contenido %}
	<h1>Contacto</h1>
	<p>
		<a href="http://twitter.com/bicitacora">@bicitacora</a>
	</p>
{% endblock %}

xbapp/templates/xbapp/estadisticas.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles %}

{% block contenido %}
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script src="{% static 'xbapp/js/graficas.js' %}"></script>
	<h1>Estadísticas</h1>
	<h2>Ciclistas registrados (falta el dato)</h2>
	<p class="lead">{{ nrutas }}</p>

	<h2>Rutas registradas</h2>
	<p class="lead">{{ nrutas }}</p>
	<div class="row">
		<div id="piechart" ></div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="progress">
					<div class="progress-bar progress-bar-primary" style="width: {{ hombres }}%">
						<span id="hombres" data-n="{{ num_hombres }}" class="sr-only">{{ hombres }} % hombres </span>
					</div>
					<div class="progress-bar progress-bar-success" style="width: {{ mujeres }}%">
						<span  id="mujeres" data-n="{{ num_mujeres }}" class="sr-only">{{ mujeres }} % mujeres</span>
					</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
		<span class="label label-primary">Hombres {{ hombres }} %</span>
		</div>
		<div class="col-md-6">
			<span class="label label-success">Mujeres {{ mujeres }} % </span>
		</div>
	</div>
	<h2>Edad media</h2>
	<p class="lead">{{ edad_media }} años</p>
	<h2>Edades por rango</h2>
	{% for edad in edades %}
		<div class="row">
			<div class="col-md-4">
				<span class="label label-primary">{{ edad.rango }} Total:{{ edad.cantidad }} </span>
			</div>

			<div class="col-md-8">
				<div class="progress">
						<div class="progress-bar progress-bar-primary" style="width: {{ edad.porcentaje }}%">
							<span class="sr-only">{{ edad.porcentaje }}%</span>
						</div>
				</div>
			</div>
		</div>
	{% endfor %}
{% endblock %}

xbapp/templates/xbapp/inicio.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles %}

{% block contenido %}
	{% addtoblock 'css' %}
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/mapa.css' %}">
	{% endaddtoblock %}

	{% addtoblock 'js' %}
		<script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=geometry"></script>
		<script src="{% static 'xbapp/js/mapa.js' %}"></script>
		<script src="{% static 'xbapp/js/mapapublico.js' %}"></script>
	{% endaddtoblock %}
	<ul class="subnav">
		<li>Revisa las rutas más usadas</li>
		<li>Datos generales</li>
	</ul>
	<div id="map_canvas"></div>
{% endblock %}

xbapp/templates/xbapp/perfil.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles bootstrap_tags %}

{% block contenido %}
	{% addtoblock 'js' %}
		<script type="text/javascript" language="javascript" src="{% static 'xbapp/js/bootstrap-datepicker.js' %}"></script>
		<script type="text/javascript" language="javascript">
			$(document).ready(function(){
				$("#perfil-form input, #perfil-form select").addClass('form-control');
			});
			$('#id_fecha_nacimiento').datepicker({
				format: 'dd/mm/yyyy'
			})
		</script>
	{% endaddtoblock %}
	{% addtoblock 'css' %}
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/datepicker.css' %}">
	{% endaddtoblock %}
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="row">
				<form id="perfil-form" class="form-horizontal" method="post">
					{% csrf_token %}
					{% form_horizontal formulario %}
					<div class="form-controls">
						<div class="col-md-10 col-md-offset-2">
							<input type="submit" value="Guardar">
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

xbapp/templates/xbapp/proyecto.html
{% extends 'xbapp/template.html' %}
{% load sekizai_tags staticfiles %}

{% block contenido %}
<div class="proyecto">
	<h1>Proyecto - Conoce más sobre Bicitácora</h1>
	<p>
	Bicitácora es un proyecto de desarrollo, conducido en el marco de Desarrollando América Latina y el primer Hackatón de datos abiertos de Xalapa (#xackaton2013) celebrado el 26 y 27 de Octubre de 2013 en la Facultad de Estadística e Informática de la Universidad Veracruzana.
	</p>
	<p>
	El reto aceptado por el grupo de desarrolladores de Xalapa consistió en una aplicación para que los ciclistas pudieran registrar las rutas locales y puntos de interés (como talleres, tiendas o baches)
	al rodar por las calles de Xalapa, generando al mismo tiempo, datos estadísticos sobre el uso de la bicicleta como medio de transporte o esparcimiento.
	</p>
	<p>
	El proyecto consiste en dos partes; una plataforma web para la visualización de datos creada con el framework Django; y una aplicación para móviles creada en Android nativo que permite al usuario registrar sus recorridos en bicicleta y puntos de interés.
	</p>
	<p>
	El grupo de trabajo conformado por estudiantes y profesores de las facultades de matemáticas, estadística e informática y del Instituto de Investigaciones en Educación de la Universidad Veracruzana; así como del sector privado y social se reunió por 24 horas seguidas para realizar Bicitácora.
	</p>
	<p>
	<h2>Diseño y Programación de la aplicación</h2>
	<ul class="list_nombres">
		<li>Abraham Toriz Cruz, estudiante de la Facultad de Matemáticas</li>
		<li>Alejandro Maldonado Navarro, estudiante de la FEI</li>
		<li>Daniel García Alvarado, estudiante e la FEI</li>
		<li>Joel Humberto Gomez Paredes, egresado de la FEI</li>
		<li>Juan Luis López Herrera, profesor de la FEI</li>
		<li>Gerardo Contreras Vega, director de la FEI</li>
		<li>Oscar García López, programador de N3XAsec</li>
	</ul>
	</p>
	<p>
	<h2>Diseño gráfico</h2>
	<ul class="list_nombres">
		<li>Iván Mejía Fabela, integrante de la comunidad Drupal en México</li>
		<li>Victor Manuel Hernández Olivera, profesor de la FEI</li>
	</ul>
	</p>
	<p>
	<h2>Logística</h2>
	<ul class="list_nombres">
		<li>Alberto Ramírez Martinell, Investigador del Instituto de Investigaciones en Educación</li>
	</ul>
	</p>
</div>
{% endblock %}

xbapp/templates/xbapp/template.html
{% load sekizai_tags staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block titulo %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/bootstrap-glyphicons.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/toastr.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'xbapp/css/front.css' %}">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		{% render_block "css" %}
		<script type="text/javascript" language="javascript" src="{% static 'xbapp/js/jquery-1.10.2.min.js' %}"></script>
	</head>
	<body>
		<div class="header">
			<div class="container">
				<div class="col-md-3">
					<img class="logo" src="{% static 'xbapp/images/logobicitacora.jpg' %}">
				</div>
				<div class="col-md-9">
					<div class="row">
						<div class="col-md-9"></div>
						<div class="col-md-3">
							<img src="{% static 'xbapp/images/ico-tw.png' %}">
							<img src="{% static 'xbapp/images/ico-fb.png' %}">
							<img src="{% static 'xbapp/images/ico-rss.png' %}">
						</div>
					</div>
				</div>
				<div class="col-md-9 menu">
					<ul class="navi">
						<li>
							<a href="{% url 'xbapp.views.inicio' %}">Inicio</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.proyecto' %}">Proyecto</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.estadisticas' %}">Estadísticas</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.captura' %}">Captura</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.contacto' %}">Contacto</a>
						</li>
					</ul>
				</div>
				<div class="col-md-9">
					<div class="title">
						{% block subtitulo %}Ayúdanos a recolectar datos sobre como usas tu bicicleta{% endblock %}
					</div>
				</div>
			</div>
		</div>
		<div class="content">
			<div class="container">
				<div class="col-md-9">
					{% block contenido %}
					{% endblock %}
				</div>
				<div class="col-md-3">
					<div class="formulario">
						{% if not user.is_authenticated %}
							<form action="{% url 'xbapp.views.login' %}" method="post">
								{% csrf_token %}
								<div class="bold subtitle">Registrate</div>
								<label for="correo">Correo:</label>
								<input id="correo" type="text" name="correo">
								<label for="password">Contraseña:</label>
								<input id="password" type="password" name="password">
								<input class="bigboton" type="submit" value="Participar">
							</form>
						{% else %}
							<strong>{{ request.user.ciclista }}</strong><br>
							<strong><a href="{% url 'xbapp.views.perfil' %}">Perfil</a></strong><br>
							<strong><a href="{% url 'xbapp.views.logout' %}">Salir</a></strong>
						{% endif %}
					</div>
					<div class="parraf"></div>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				<ul class="navf">
						<li>
							<a href="{% url 'xbapp.views.inicio' %}">Inicio</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.proyecto' %}">Proyecto</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.estadisticas' %}">Estadísticas</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.captura' %}">Captura</a>
						</li>
						<li>
							<a href="{% url 'xbapp.views.contacto' %}">Contacto</a>
						</li>
				</ul>
			</div>
		</div>

		<!-- javascript -->
		<script type="text/javascript" language="javascript" src="{% static 'xbapp/js/less-1.5.0.min.js' %}"></script>
		<script type="text/javascript" language="javascript" src="{% static 'xbapp/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" language="javascript" src="{% static 'xbapp/js/toastr.min.js' %}"></script>
		{% if messages %}
			<script type="text/javascript">
				toastr.options = {
					"closeButton": true,
					"positionClass": "toast-top-full-width",
				}
				{% for message in messages %}
					toastr.{{ message.tags }}('{{ message }}');
				{% endfor %}
			</script>
		{% endif %}
		{% render_block "js" %}
		
		
		
		
		
		
		
		
	</body>
</html>